### ISSUE TITLE
Why is Class soooooo......

### ISSUE THREAD

**Issue by michaelmusick** [Montana-Media-Arts/441-WebTech#2]
Please respond to this issue, right now!
Also, please call out, using the @ notation, who ever is above you.

**Comment by Br0210** [comment]
get good

**Comment by Br0210** [comment]
Get help from the teacher @michaelmusick

**Comment by CEFSTUDIO** [comment]
fantastic @michaelmusick

**Comment by goodrichnic** [comment]
Shut it down! @CEFSTUDIO

**Comment by ColbyJackL** [comment]
# WOw

**Comment by mf217126** [comment]
Hi! @ColbyJackL

**Comment by SN0WH0USE** [comment]
catch me outside @CEFSTUDIO

**Comment by ColbyJackL** [comment]
@CEFSTUDIO Easyyyyyyyyy
