### ISSUE TITLE
HW-3 Submission Forum

### ISSUE THREAD

**Issue by JonSwallow** [Montana-Media-Arts/441-WebTech#8]
Is anyone else not seeing the forum up for week 3 on Moodle?

![screenshotmoodle](https://user-images.githubusercontent.com/31550331/36119773-4044ca4a-0ffe-11e8-9a9b-afbbe69b7838.jpg)

**Comment by EllenMorningstarUM** [comment]
HAhahaha! I was literally coming here to post this to the issue board! I thought it was my browser, but after testing on Safari, Mozilla and Chrome I realized it just wasn't available yet!

**Comment by michaelmusick** [comment]
All fixed. Thank you for letting me know. The forum is now up.
